foodie/urls.py
# foodie/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include('sandbox.urls')),
    path('',  include('foodie_app.urls')),
    path('recipes/', include('recipes.urls')),
    path('comments/', include('comments.urls')),
    path('accounts/', include('accounts.urls'))
]

sandbox/urls.py
# sandbox/urls.py
from django.urls import path
from . import views

app_name = "sandbox"
urlpatterns = [
    path("", views.index, name="index"),
    path("recipes/", views.RecipeListView.as_view(), name="recipe_list"),
    path("recipes/<int:pk>", views.RecipeDetailView.as_view(), name="recipeDetail"),
    path("refreshing/", views.SpecificRecipesView.as_view(), name="refreshing_recipes"),
    path("feedback/", views.feedback, name ="feedback"),
    path("thank-you/", views.thank_you, name="thank_you")
]

sandbox/models.py
# sandbox/models.py
from django.db import models

class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    feedback = models.TextField()
    satisfaction = models.CharField(max_length=10)

    def __str__(self):
        return self.name
    

sandbox/forms.py
# sandbox/forms.py
from django import forms

choices = [
    ("happy", "Happy"), ("neutral", "Neutral"), ("sad", "Sad")
]

class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    feedback = forms.CharField()
    satisfaction = forms.ChoiceField(choices=choices, widget=forms.RadioSelect)

    def clean_email(self):
        email = self.cleaned_data['email']
        if "@gmail.com" not in email:
            raise forms.ValidationError("Please use your gmail email")
        return email

sandbox/views.py
# sandbox/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, View

from recipes.models import Recipe
from sandbox.forms import FeedbackForm
from sandbox.models import Feedback

# Function based View
## data = ["Pizza", "Pasta", "Salad", "Bread"]
## context = {"foods", data}
data = Recipe.objects.all()
context = {"recipes": data}
# Create your views here.
def index(request):
    return render(request, "sandbox/index.html", context)

# Class-based View
class RecipeListView(ListView):
    model = Recipe
    template_name = "sandbox/index.html"
    context_object_name = "recipes"
    
    def get_queryset(self):
        filtered_recipes = Recipe.objects.filter(category__name_iexact="Salad")
        return filtered_recipes
    
class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "sandbox/recipeDetail.html"
    context_object_name = "recipe"

def thank_you(request):
    return HttpResponse("Thank you for feedback!")

def feedback(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            # process the form
            # print(form.cleaned_data)
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            feedback = form.cleaned_data['feedback']
            satisfaction = form.cleaned_data['satisfaction']
            Feedback.objects.create(
                name = name,
                email = email,
                feedback = feedback,
                satisfaction = satisfaction
            )
            return redirect("sandbox:thank_you")
    else:
        form = FeedbackForm()

    context = {"form": form}
    return render(request, "sandbox/feedbacK_form.html", context)


## Customized View
class SpecificRecipesView(View):
    def get(self, request, *args, **kwargs):
        ## fetch recipes with "refreshing" in the description
        refreshing_recipes = Recipe.objects.filter(description__icontains="refreshing")
        context = {"refreshing": refreshing_recipes}
        return render(request, 'sandbox/refreshing_recipes.html', context)

sandbox/templates/sandbox/feedback_form.html
{% extends "base.html" %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

sandbox/templates/sandbox/index.html
{% extends "base.html" %}
{% block content %}

    {% if recipes %}
        <ul>
            {% for recipe in recipes %}
                <li>
                    <a href="{% url "sandbox:recipeDetail" recipe.id %}"> {{ recipe.name }} </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p> No reciped found. </p>
    {% endif %}

{% endblock content %}

sandbox/templates/sandbox/recipeDetail.html
{% extends "base.html" %}
{% block content %}

    {% if recipe %}
        <article>
            <h2>{{ recipe.name }} </h2>
            Description: <p> {{ recipe.description }} </p>
            Ingredients: <p> {{ recipe.ingredients }} </p>
            Directions: <p> {{ recipe.directions }} </p>
        </article>
    {% else %}
        <p> No recipes found. </p>
    {% endif %}

{% endblock content %}

sandbox/templates/sandbox/refreshing_recipes.html
{% extends "base.html" %}
{% block content %}

    {% if refreshing %}
        <ul>
            {% for recipe in refreshing %}
                <li>
                    <a href="{% url "sandbox:recipeDetail" recipe.id %}"> {{ recipe.name }} </a>
                    Description:
                    <pre>{{ recipe.description}}</pre>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p> No reciped found. </p>
    {% endif %}

{% endblock content %}