foodie/urls.py
# foodie/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include('sandbox.urls')),
    path('',  include('foodie_app.urls')),
    path('recipes/', include('recipes.urls')),
    path('comments/', include('comments.urls')),
    path('accounts/', include('accounts.urls'))
]

foodie_app/urls.py
# foodie_app/urls.py
from django.urls import path
from . import views

app_name = "foodie_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("recipes/<int:category_id>/", views.recipes, name="recipes"),
    path("add-category/", views.add_category, name="add_category"),
    path("add_recipe/", views.add_recipe, name="add_recipe_no_genre"),
    path("add_recipe/category/<int:category_id>", views.add_recipe, name="add_recipe_with_genre")
]

recipes/urls.py
# recipes/urls.py
from django.urls import path
from recipes import views

app_name = "recipes"
urlpatterns = [
    # Adding pattern name in the end of each path PLEASE,
    # as such, serving the calling from recipes.html.
    path("", views.recipes, name="index"),
    path("<int:recipe_id>", views.recipe, name="recipe_detail"),
]

foodie_app/models.py
# foodie_app/models.py
from django.db import models

# Create Category model
class Category(models.Model):
    name = models.CharField(max_length=100)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ## in descending order per 'name' or 'date_added'
        ordering = ["-date_added"]
        verbose_name = "Category"
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.name

recipes/models.py
# recipes/models.py
from django.db import models
from foodie_app.models import Category

# Create Recipe model
class Recipe(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    ingredients = models.TextField()
    directions = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name   

foodie_app/forms.py
# foodie_app/forms.py
from django import forms
from foodie_app.models import Category
from recipes.models import Recipe

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]
        labels = {"name": "Category Name"}
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Category Name'})
        }

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["name", "description", "ingredients", "directions", "category"]
        labels = {"name": "Recipe Title"}
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Recipe Title'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description', 'rows': '5'}),
            'ingredients': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingredients', 'rows': '5'}),
            'directions': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Directions', 'rows': '5'}),
            'category': forms.Select(attrs={'class': 'form-select'})
        }

foodie_app/views.py
# foodie_app/views.py
from django.shortcuts import get_object_or_404, redirect, render

from foodie_app.forms import CategoryForm
from .models import Category
from recipes.models import Recipe
from foodie_app.forms import RecipeForm

# Create your views here.
def index(request):
    categories = Category.objects.all()
    context = {"categories": categories}

    return render(request, "foodie_app/index.html", context)

def recipes(request, category_id):
    recipes = Recipe.objects.filter(category=category_id)
    category = Category.objects.get(pk=category_id)

    context = {"recipes": recipes, "category": category}
    return render(request, "foodie_app/recipes.html", context)

def add_category(request):
    if request.method == "POST":
        # print(request.POST)
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("foodie_app:index")
        else:
            context = {"form": form}
            return render(request, "foodie_app/add_category.html", context)
    else:
        form = CategoryForm
        context = {"form": form}
        return render(request, "foodie_app/add_category.html", context)
    
def add_recipe(request, category_id=None):
    category=None
    if category_id:
        # category = Category.objects.get(pk=category_id)
        category = get_object_or_404(Category, id=category_id)
        form = RecipeForm(request.POST or None, initial={"category": category})
    else:
        form = RecipeForm(request.POST or None)
    
    if request.method =="POST" and form.is_valid():
        new_recipe = form.save()
        return redirect("foodie_app:recipes", category_id=new_recipe.category.id)
    
    context = {
        "form": form,
        "category": category
    }
    return render(request, "foodie_app/add_recipe.html", context)

recipes/views.py
# recipes/views.py
from django.shortcuts import render
from recipes.models import Recipe

# Create your views here.
def recipes(request):

    recipes = Recipe.objects.all()
    context = {"recipes": recipes}
    return render(request, "recipes/recipes.html", context)

def recipe(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    context = {
        "recipe": recipe
    }
    return render(request, "recipes/recipeDetails.html", context)

foodie_app/templates/foodie_app/add_category.html
{% extends "base.html" %}
{% block content %}
    <h3>Add Category</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p}}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock content %}

foodie_app/templates/foodie_app/add_recipe.html
{% extends "base.html" %}
{% block content %}
    <h3>Add a new Recipe 
        {% if category %}to {{ category.name }}{% endif%}
    </h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save Recipe</button>
        </form>
    </div>
{% endblock content %}

foodie_app/templates/foodie_app/index.html
{% extends "base.html" %}
{% block content %}
    <h3>Categories</h3>
    <div>
        <a href="{% url "foodie_app:add_category" %}">Add Category </a>
        {% for category in categories %}
            <div>
                <a href="{% url "foodie_app:recipes" category.id %}"> {{ category }} </a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

foodie_app/templates/foodie_app/recipes.html
{% extends "base.html" %}
{% block content %}
    <h3>Recipes under <i>{{ category }}</i> </h3>
    <a href="{% url "foodie_app:add_recipe_with_genre" category_id=category.id %}">Add Recipe</a>
    <div>
        {% for recipe in recipes %}
            <div>
                <div>
                    <h5> {{ recipe.name }} </h5>
                    <p> {{ recipe.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}